export const ADD_CAR_DETAILS_REQ = "ADD_CAR_DETAILS_REQ";
export const ADD_CAR_DETAILS_REQ_SUCCESS = "ADD_CAR_DETAILS_REQ_SUCCESS";
export const ADD_CAR_DETAILS_REQ_FAILURE = "ADD_CAR_DETAILS_REQ_FAILURE";
